### PR TITLE
Port to wgpu

### PR DESCRIPTION
**Pull request by Kl4rry**

### CODE REVIEW

**Comment by Kl4rry** [comment]
@0323pin How is vulkan support on NetBSD? The OpenGL backend of wgpu is kinda scuffed. Like it segfaults if multiple threads are used.

**Comment by 0323pin** [comment]
@Kl4rry Honestly, I don't know.
Do you want me to try a build from 9c94202818c614a987bd20e077ae9243a5129e81?
I can do that.

**Comment by Kl4rry** [comment]
Yes that would be nice. You can force it to use vulkan by using the env var `WGPU_BACKEND=vulkan`.

**Comment by 0323pin** [comment]
It builds fine,
```
===> Building for simp-3.4.1
   Compiling libc v0.2.152
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling pkg-config v0.3.29
   Compiling proc-macro2 v1.0.76
   [...]
   Compiling simp v3.4.1 (/usr/pkgsrc/wip/simp/work/simp-9c94202818c614a987bd20e077ae9243a5129e81)
   Compiling egui-winit v0.25.0
   Compiling ctrlc v3.4.2
   [...]
   Finished release [optimized] target(s) in 15m 55s
```

But ...
```
~> simp nik-5lzJbDKElQ8-unsplash.jpg
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF-8" (mapped to "en_US.UTF-8")
PanicInfo { payload: Any { .. }, message: Some(tessellate called before first call to Context::run()), location: Location { file: "/usr/pkgsrc/wip/simp/work/vendor/egui-0.25.0/src/context.rs", line: 1813, col: 18 }, can_unwind: true, force_no_backtrace: false }
Exception: simp exited with 1
```

```
$ export WGPU_BACKEND=vulkan
$ simp max-burgi-3e-Hdr5csOg-unsplash.jpg
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF-8" (mapped to "en_US.UTF-8")
PanicInfo { payload: Any { .. }, message: Some(tessellate called before first call to Context::run()), location: Location { file: "/usr/pkgsrc/wip/simp/work/vendor/egui-0.25.0/src/context.rs", line: 1813, col: 18 }, can_unwind: true, force_no_backtrace: false }
```

I wouldn't bother with the `xkbcommon` error, I get the same launching `alacritty` and it works fine.

**Comment by Kl4rry** [comment]
Interesting. The same panic appears under some conditions on windows so I have likely done something worng.

**Comment by 0323pin** [comment]
Ok, do you want to dig into it first and ping me for a new build soon or, how should we proceed?

**Comment by Kl4rry** [comment]
Yes, you can try this fed093c833b3d17cb79b43fa440de3f1cfea5750 commit. It fixed the crash on windows.

**Comment by 0323pin** [comment]
@Kl4rry It works now :)

2024-01-24-055748_1366x768_scrot

Also, when using,
```
$ export WGPU_BACKEND=vulkan
$ simp sung-jin-cho-p3g6hLNMAGw-unsplash.jpg
```

If I'm using this correctly, that's another question :)

**Comment by Kl4rry** [comment]
Good that it works. But I not 100% sure it's actually running on vulkan. Its not really clear from the docs which one is picked the desired one is not available.

**Comment by 0323pin** [comment]
I'm not sure it's using vulkan either. Anyway to check?
No rush, I'm out tonight.

**Comment by 0323pin** [comment]
Did you find out how to check which back-end is being used?

2024-01-25-230501_1366x768_scrot

**Comment by Kl4rry** [comment]
Yes, 854b4eb this commit should display the used backend in the about menu. It should also force netbsd to use vulkan so I think it should crash if it is not working.

**Comment by 0323pin** [comment]
@Kl4rry Building from 854b4ebd4b127d295c82515f55c2ed3ad5321a6d,

```
error: failed to run custom build command for `simp v3.4.1 (/usr/pkgsrc/wip/simp/work/simp-854b4ebd4b127d295c82515f55c2ed3ad5321a6d)`

Caused by:
  process didn't exit successfully: `/usr/pkgsrc/wip/simp/work/simp-854b4ebd4b127d295c82515f55c2ed3ad5321a6d/target/release/build/simp-f98a220f742dd588/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=GIT_HASH=54f8e8919791c01c292f495d7a1a43db812ab338

  cargo:rerun-if-changed=Cargo.toml

  --- stderr
  error: no such command: `about`

  	Did you mean `audit`?

  	View all installed commands with `cargo --list`
  	Find a package to install `about` with `cargo search cargo-about`
  error: no such command: `about`

  	Did you mean `audit`?

  	View all installed commands with `cargo --list`
  	Find a package to install `about` with `cargo search cargo-about`
  thread 'main' panicked at build.rs:58:9:
  assertion failed: exit_status.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
*** Error code 101

Stop.
```

Same from 18b7458ac69844b633279e8aaff1ca42c94dee1e

**EDIT:** I've packaged and merged [cargo-about](https://github.com/EmbarkStudios/cargo-about), re-building from 18b7458ac69844b633279e8aaff1ca42c94dee1e now.

**EDIT_2:**
It builds now,
```
warning: unused variable: `instance_descriptor`
  --> src/main.rs:92:13
   |
92 |         let instance_descriptor = wgpu::InstanceDescriptor {
   |             ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_instance_descriptor`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `simp` (bin "simp") generated 1 warning (run `cargo fix --bin "simp"` to apply 1 suggestion)
    Finished release [optimized] target(s) in 11m 55s
```

But, vulkan doesn't seem to be supported.

2024-01-26-094858_1366x768_scrot

It's the same even when setting `WGPU_BACKEND=vulkan`

**Comment by Kl4rry** [comment]
Aight then, I will just keep supporting the GL backend.

**Comment by 0323pin** [comment]
> Aight then, I will just keep supporting the GL backend.

Thank you!

**Comment by 0323pin** [comment]
@Kl4rry Thank you for your work and for supporting NetBSD.

I've asked internally and the vulkan driver is still absent. There was a [bounty](https://wiki.netbsd.org/projects/project/mesavulkan/) over a year ago but, apparently no one has volunteered 😞

**Comment by Kl4rry** [comment]
Its not too much trouble. OpenGL still has some advantages for some weird reason on windows. It has faster startup and has less flickering when resizing the window. But mip maps are broken in the wgpu OpenGL backend.

**Pull request merged**
